name: harmonymusic
description: A cross platform app for music streaming.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.12.2+27

environment:
  sdk: ">=3.1.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animations: ^2.0.11
  app_links: ^3.5.1
  archive: ^3.1.6
  audio_service: ^0.18.17
  audio_service_mpris: ^0.1.5
  audio_video_progress_bar: ^2.0.3
  audiotags: ^1.4.1
  buttons_tabbar: ^1.3.13
  cached_network_image: ^3.4.0
  dio: ^5.7.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_lyric: ^2.0.4+6
  flutter_slidable: ^3.1.2
  get: ^4.7.1
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.6
  ionicons: ^0.2.2
  jni: ^0.14.0
  just_audio: ^0.9.46
  just_audio_media_kit:
    git:
      url: https://github.com/anandnet/just_audio_media_kit.git
      ref: 6672eb82657d9e671abbf42122031c88aa9e6d80
  palette_generator: ^0.3.3+4
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  share_plus: ^10.1.4
  package_info_plus: ^8.0.0
  wakelock_plus: ^1.3.3
  shimmer: ^3.0.0
  sidebar_with_animation:
    git:
      url: https://github.com/anandnet/animated_side_bar.git
      branch: main
      ref: b53567a42b4ba3793a3cf00d478bdba0ecce33d7
  smtc_windows: ^0.1.2
  terminate_restart:
    git:
      url: https://github.com/anandnet/terminate_restart.git
      branch: main
      ref: eb505e07e11d0fe1f5c03993e707c6678428c353
  toggle_switch: ^2.1.0
  tray_manager: ^0.2.3
  url_launcher: ^6.2.1
  widget_marquee: ^0.0.8
  window_manager: ^0.4.2
  youtube_explode_dart:
    git:
      url: https://github.com/anandnet/youtube_explode_dart.git
      ref: 1d9ec9baa806705b1d859260eeb389ec28c6b024
dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  jnigen: ^0.14.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
