on: push
name: cleans, build and test app (mobile - android)
jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: clean stale build and cache
      uses: ./action
      with:
        args: clean

    - name: install dependencies
      uses: ./action
      with:
        args: pub get

    - name: build apk
      uses: ./action
      with:
        args: build apk --release
